#!/bin/sh

set -e

cd "$(dirname "$(readlink -f "$0")")"

main() {
    echo
    date --utc +'-------------------- %a, %0e %b %Y %H:%M:%S %z --------------------'
    . env/bin/activate
    ./autosubmit.py
}

main >>autosubmit.log 2>&1
