#!/bin/sh

set -e

main() {
    echo
    date --utc +'-------------------- %a, %0e %b %Y %H:%M:%S %z --------------------'
    cd "$(dirname "$(readlink -f "$0")")"
    ./autosubmit.py
}

main >>autosubmit.log 2>&1
